server:
  port: 8082
spring:
  application:
    name: payment-application
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8721/eureka/