server:
  port: 8081
spring:
  application:
    name: inventory-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8721/eureka/