server:
  port: 8080
spring.cloud.stream:
  function:
    definition: supplier;consumer
  bindings:
    supplier-out-0:
      destination: order-created
    consumer-in-0:
      destination: order-updated
spring:
  application:
    name: order-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8721/eureka/